### ISSUE TITLE
[CI/CD] Enhance pipeline for production readiness

### ISSUE THREAD

**Issue by democratize-technology-code-reviewer** [democratize-technology/node-grocy#18]
## Overview
Enhance the existing GitHub Actions workflows for comprehensive CI/CD. Add multi-Node.js version testing, automated npm publishing, security scanning, and performance benchmarking.

## Objectives
- Test against multiple Node.js versions (18, 20, 22)
- Set up automated npm publishing on version tags
- Add security scanning and dependency updates
- Implement performance benchmarking

## Definition of Done
- [ ] GitHub Actions test matrix includes Node.js 18, 20, 22
- [ ] All tests pass on all supported Node.js versions
- [ ] Automated npm publish workflow on version tags
- [ ] Security scanning integrated (npm audit in CI)
- [ ] Dependency update automation configured (Dependabot/Renovate)
- [ ] Performance benchmarks run on every PR
- [ ] Code coverage reports published to Codecov/Coveralls
- [ ] Build artifacts automatically generated
- [ ] Release notes auto-generated from commits
- [ ] CI/CD documentation updated with new workflows

## Test Matrix Configuration
```yaml
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        include:
          - node-version: 20.x
            coverage: true
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      
      - name: Run tests
        run: npm test
        
      - name: Run tests with coverage
        if: matrix.coverage
        run: npm run test:coverage
        
      - name: Upload coverage
        if: matrix.coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
```

## NPM Publishing Workflow
```yaml
name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      
      - run: npm ci
      - run: npm run build
      - run: npm test
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

## Security Scanning
```yaml
name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      
      - name: npm audit
        run: npm audit --audit-level=moderate
        
      - name: Check for known vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```

## Performance Benchmarking
```yaml
name: Benchmark

on:
  pull_request:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      
      - run: npm ci
      - run: npm run build
      
      - name: Run benchmarks
        run: npm run benchmark
        
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'benchmarkjs'
          output-file-path: benchmark-results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '110%'
          comment-on-alert: true
          fail-on-alert: true
```

## Dependency Updates (Renovate)
```json
{
  "extends": [
    "config:base"
  ],
  "packageRules": [
    {
      "matchDepTypes": ["devDependencies"],
      "automerge": true
    },
    {
      "matchUpdateTypes": ["patch"],
      "automerge": true
    }
  ],
  "schedule": ["before 3am on Monday"],
  "prConcurrentLimit": 3,
  "prCreation": "immediate"
}
```

## Release Automation
```yaml
name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

## Benchmark Script
```json
{
  "scripts": {
    "benchmark": "node benchmarks/index.js",
    "benchmark:ci": "node benchmarks/index.js --reporter json > benchmark-results.json"
  }
}
```

## Related Issues
Blocks:
- #18 - Plan v1.0.0 release strategy and migration

## Code Lift
Medium - This is primarily configuration work, but requires careful setup and testing of all workflows. Estimated 8-12 hours.
